SELECT * FROM clinica.medico;


SELECT * FROM clinica.ESPECIALIDADE;
SELECT * FROM clinica.CONSULTA;
SELECT * FROM clinica.PACIENTE;
SELECT * FROM CLINICA.TELEFONE;
SELECT * FROM CLINICA.POSSUIESPECIALIDADE;

UPDATE CLINICA.PACIENTE
SET ESTADO = 'RJ'
WHERE ID = 6;